name: Publish docs update

on:
  push:
    branches: [beta7, early, stable7]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Rebuild site
        run: |
          curl -X POST https://api.github.com/repos/plentymarkets/plenty-developers-docs/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          --user 'plentymonkey:${{ secrets.PLENTYMONKEY_TOKEN }}' \
          --data '{"event_type": "ContentSourceUpdate", "client_payload": { "repository": "${{ github.repository }}" }}'
